name=SlewRateLimiter
version=1.0.0
author=JamalMeizongo
maintainer=mrmeizongo
sentence=Simple slew rate limiter written in C++
paragraph=Simple slew rate limiter written in C++
category=Signal Control
url=https://github.com/mrmeizongo/SlewRateLimiter.git
architectures=*
